stfc/janus-core

janus_core/mlip_calculators.py
janus_core/single_point.py
tests/test_mlip_calculators.py

Resolves #40
Note: There may be a way to pass device to chgnet as well, but currently this makes things consistent between MACE, m3gnet and most likely other PyTorch-based models.
Also tidies single point calculation and calculator code addressing comments in #32.

Specify device consistently

---

.github/workflows/ci.yml
.github/workflows/publish-on-pypi.yml

Resolves #41
Note: poetry is still installed with the same version of Python (3.10.12) for each job, but I don't think this is a problem, and the virtual environment created by poetry appears to use the correct Python version.

Fix Python versions in CI

---

.pre-commit-config.yaml
pyproject.toml

Sets all maximum line lengths to 88, matching the default for black, which we have implicitly been using so far.
We could increase is slightly if there is strong preference, but otherwise I'd suggest `fmt: off` or `# fmt: skip` should be sufficient for rare exceptions.

Harmonise max line lengths

---

.github/workflows/ci.yml
.gitignore
pyproject.toml

Resolves #46
While technically #46 was addressed by changes on coveralls settings (no minimum coverage or maximum decrease), this seems to fix the coverage detected by coveralls. 
Neither the original "100%" coverage nor the current 77% coverage match the coverage output during local tests and the CI.
These changes seem to fix that: https://coveralls.io/builds/66090622

Fix coverage read by coveralls

---

janus_core/mlip_calculators.py
tests/test_mlip_calculators.py

Resolves issue with duplicated `kwargs` for `mace_off` and `mace_mp`.
The new tests throws an error without the fix, e.g.:
```python
E       TypeError: mace.calculators.mace.MACECalculator() got multiple values for keyword argument 'model_paths'
../venv_janus_11_new/lib/python3.11/site-packages/mace/calculators/foundations_models.py:105: TypeError
------------------------------------------------------- Captured stdout call --------------------------------------------------------
Using Materials Project MACE for MACECalculator with /home/ek/.cache/mace/46jrkm3v
Using float64 for MACECalculator, which is slower but more accurate. Recommended for geometry optimization.
====================================================== short test summary info …
```

Fix duplicate model_paths kwarg

---

janus_core/cli.py
janus_core/single_point.py
tests/test_cli.py
tests/test_geom_opt.py
tests/test_single_point.py

Resolves #47
As mentioned  in #49, my preference is not to overload something like `read_struct`, as was originally proposed in #47, but to separate reading from file (which could be overloaded for non-ASE readers) with passing a structure directly (which could also include non-ASE objects in future).
This is largely to enable changing the confusingly named `structure` (as opposed to `struct`) attribute to `struct_path`.

Add option to pass Atoms structure directly

---

.gitignore
docs/source/apidoc/janus_core.rst
janus_core/cli.py
janus_core/janus_types.py
janus_core/log.py
janus_core/single_point.py
tests/test_cli.py

Resolves #52
Adds a skeleton for logging, that currently just captures the start and end times for the single point calculation and saves to a log file, so the CLI behaves as expected for aiida-mlip.
I'm not sure there's a way to test the log file more rigorously, as pytest seems to interfere, but it at least tests the contents of the log.

Add logger skeleton

---

janus_core/single_point.py
tests/test_single_point.py

Resolves #66
Ideally, we'd probably remove the separate `results` dictionary and rely on clean-up of `calc.results`, but we would still need something of similar form in order to return lists of properties for trajectories.
An alternative could be to remove setting results until after clean-up, but then we don't make use of the values returned by `Atoms.get_potential_energy` etc. This might still be slightly tidier, but is perhaps slightly more dangerous too given that MACE sets multiple results simultaneously, so in many cases, `energy` would be taken from the results from `get_stress`.

Fix removing NaN results

---

janus_core/mlip_calculators.py
tests/test_geom_opt.py
tests/test_mlip_calculators.py
tests/test_single_point.py

As reported by @federicazanca, currently if you specify `model` rather than `model_paths` in `kwargs` for `mace_mp`, it will default to using `"small"`, as it expects the value to only be defined through `model_paths`.
This can be confusing, as `mace_mp` (and `mace_off`, but that doesn't accept paths in the expected way anyway) expects the `model` keyword.
These changes ensure only one of `model_paths` and `model` are specified, but allows either to be defined.
Also changes `model_paths` to `model` in various places (mostly tests), as I think it's usually more accurate, particularly as `mace_mp` is our default.

Fix model path kwargs

---

README.md
janus_core/cli.py
janus_core/geom_opt.py
janus_core/log.py
janus_core/single_point.py
tests/test_geom_opt.py
tests/test_geomopt_cli.py
tests/test_single_point.py
tests/test_singlepoint_cli.py
tests/utils.py

Resolves #65
See issue for remaining work.
This also implements the logger in geom_opt.py slightly differently to single_point.py, in order to pass kwargs (specifically, to allow appending rather than write only). It probably makes sense to update single_point.py to match this too.

Add geomopt to CLI

---

pyproject.toml
tox.ini

- Fixes python path so tests.utils module is found correctly
- Adds python 3.11 tests which I had erroneously removed
- Adds `posargs` to pytest to enable additional arguments to be passed e.g. `tox run -- tests/test_singlepoint_cli.py::test_janus_help` to run an individual test

Fix tox configuration

---

janus_core/cli.py
janus_core/geom_opt.py
tests/test_geomopt_cli.py

Adds `--opt` flag, similar to `--traj` flag, to specify the path to save the optimized structure
Also tidies other parts of the CLI, including
- Allows `--vectors-only` without `--fully-opt`
- Tidies help/docstrings
- Fix full docstring being printed with `--help`
- Clarify how to pass `kwargs` via CLI

Add CLI option for geomopt structure path

---

janus_core/mlip_calculators.py

This will address errors with MACE-OFF due to a change of URL, but currently only fixes a misleading error if no model is specified for "mace" (`TypeError: object of type 'NoneType' has no len()` -> `ValueError: No mace file names supplied`)

Fix MACE model

---

.gitignore
janus_core/cli.py
janus_core/geom_opt.py
janus_core/log.py
janus_core/md.py
pyproject.toml
tests/test_geom_opt.py
tests/test_geomopt_cli.py
tests/test_log.py
tests/test_md.py
tests/test_md_cli.py
tests/test_singlepoint_cli.py
tests/utils.py

Resolves #64
Initial part of possible solution to extending logging. When using the CLI (MD, since the kwargs were already prepared), this outputs something like:
```
- command: janus md
- start_time: 27/03/2024, 12:38:24
- inputs:
barostat_time: 75.0
bulk_modulus: 2.0
ensemble: nve
equil_steps: 0
file_prefix: null
friction: 0.005
log_kwargs:
filemode: a
filename: md.log
minimize: true
minimize_every: 1
minimize_kwargs: {}
pressure: 0.0
remove_rot: false
rescale_every: 10
rescale_velocities: false
restart: false
restart_every: 1000
restart_stem: null
restarts_to_keep: 4
rotate_restart: false
seed: null
stats_every: 100
stats_file: null
steps: 2
struct:
formula: Cl4Na4
n_atoms: 8
struct_path: tests/data/NaCl.cif
struct_name: NaCl
temp: 300.0
thermostat_time: 50.0
timestep: 1.0
traj_append: …
```

Extend logging

---

.github/scripts/check_version.py
.github/workflows/publish-on-pypi.yml
janus_core/cli.py
tests/test_cli.py
tests/test_geomopt_cli.py
tests/test_md_cli.py
tests/test_singlepoint_cli.py

Resolves #77 and #78
- Adds `--version` option for CLI, which outputs `__version__` from `janus_core/__init__`
- Includes minor change in behaviour so that the `--help` output is produced when running only `janus`, rather than `Error: Missing command`.
- This is partly because with the version callback, it's not straightforward to produce the same output as previously, but it also seems like a reasonable output to me
- Adds check that the version in `__init__.py` matches the version in `pyproject.toml` and the git tag, when running the `publish-on-pypi` workflow
- Initially considered using `janus --version`, which is why it became part of this change, but that requires installing janus, which seemed unnecessary.
- Could be split into a different PR if there's anything controversial

Add janus CLI version option

---

janus_core/cli.py
tests/test_geomopt_cli.py
tests/test_md_cli.py
tests/test_singlepoint_cli.py

Resolves #101
Also removes the duplicate `struct_path` for singlepoint summary, which isn't present in geomopt/md since the singlepoint options are instead explicitly captured under `inputs["calc"]`
E.g. singlepoint_summary is now:
```yaml
command: janus singlepoint
inputs:
architecture: mace_mp
calc_kwargs: {}
device: cpu
log: singlepoint.log
read_kwargs: {}
run:
properties: []
write_kwargs: {}
struct:
formula: Cl4Na4
n_atoms: 8
struct_name: NaCl
struct_path: tests/data/NaCl.cif
start_time: 08/04/2024, 18:27:48
end_time: 08/04/2024, 18:27:49
```
Previously:
```yaml
- command: janus singlepoint
- start_time: 08/04/2024, 18:34:19
- inputs:
architecture: mace_mp
calc_kwargs: {}
device: cpu
log: singlepoint.log
read_kwargs: {}
run:
properties: []
write_kwargs: {}
struct:
formula: Cl4Na4 …
```

Change CLI summary to dict from list

---

janus_core/__init__.py

This should mean we only need to change the version in one place.
Note: it updates when `poetry install` (or similar) is run, but I think that should be fine.

Define __init__ version via pyproject.toml

---

README.md
docs/source/conf.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/singlepoint.py
janus_core/cli/utils.py
tests/data/invalid.yml
tests/test_geomopt_cli.py
tests/test_md_cli.py
tests/test_singlepoint_cli.py

Resolves #103
Compares the options defined in configuration file to CLI function options to ensure only valid options are defined.
Also restructures code, as the CLI module was getting a bit unwieldy. This is entirely done within the first commit, so happy to separate out into two PRs if preferable.

Ensure config options are valid

---

README.md
janus_core/calculations/md.py
tests/test_md.py

The desired behaviour introduced is to produce a restart file (```.xyz```) at the end of a heating cycle or md run. As discussed in #108 the user specified restart frequency may not align with the final time step, and this results in a predictable file name for use in automated meta-workflows.
Schematically the file stems will be (NPT is currently no working in this PR),
```
[ENSEMBLE]-[TEMPERATURE]-[STEP]-res
[ENSEMBLE]-[TEMPERATURE]-final
[ENSEMBLE]-[TEMPERATURE]-[STEP]-res
[ENSEMBLE]-[TEMPERATURE]-final
[ENSEMBLE]-[TEMPERATURE_START]-[TEMPERATURE_END]-stats
[ENSEMBLE]-[TEMPERATURE_START]-[TEMPERATURE_END]-traj
[ENSEMBLE]-[TEMPERATURE]-[PRESSURE]-final
[ENSEMBLE]-[TEMPERATURE_START]-[TEMPERATURE_END]-[PRESSURE]-stats
```
@ElliottKasoar One point that definitely needs addressing is what …

Add final restart files, and fixed heating file stems

---

.github/scripts/check_version.py
.github/workflows/publish-on-pypi.yml

Resolves #125
Removes `__init__.py`  version check from publish workflow, as we no longer specify this manually.

Remove __init__ version check

---

docs/source/apidoc/janus_core.rst
docs/source/conf.py
janus_core/cli/janus.py
janus_core/cli/train.py
janus_core/helpers/train.py

Resolves #36
Adds training (for MACE, but extensible), currently by passing the configuration file straight through to the MLIP training.
No tests currently as this depends on MACE's develop branch. We could change the pyproject.toml dependency, but the required changes should be merged to main and tagged in the next couple of weeks.

Add training for MACE

---

janus_core/cli/md.py
tests/test_md_cli.py

This doesn't resolve #129, but I think it addresses setting the structure name more straightforwardly than #136.
I would suggest we either remove `file_prefix`, or (preferably, in my opinion) fix the results/final files that no longer respect use it in the way other files do.

Add structure name option to MD CLI

---

tests/test_md_cli.py

Currently the log file/summary paths for this test are unspecified, so the default values are used.
This means the files remain once the test has run, as they are not placed in a temporary directory as we do elsewhere.

Fix saving MD log/summary in test

---

janus_core/calculations/geom_opt.py
janus_core/cli/geomopt.py
tests/test_geomopt_cli.py

Resolves #152
As discussed in the issue, we may want a more general kwargs (filter-kwargs, or even more generally minimize-kwargs) to allow further options to be set e.g. `constant_volume` (happy to address that in this PR, or open a new issue).

Add pressure option for geomopt

---

README.md
janus_core/calculations/single_point.py
tests/data/singlepoint_config.yml
tests/test_single_point.py
tests/test_singlepoint_cli.py

Resolves #114
Tests are modified so that where previously we had to specify `index=":"` via read_kwargs, the same result is obtained by default, while specifying the index is instead tested by choosing a single structure from a trajectory.

Read all structures in trajectory by default

---

janus_core/calculations/md.py
janus_core/cli/md.py
janus_core/cli/types.py
tests/test_md.py
tests/test_md_cli.py

Add integrator kwargs to MD

---

janus_core/calculations/single_point.py

remove nans for real now

---

pyproject.toml

Resolves #196
This doesn't seem to affect any phonopy functionality from initial testing e.g. from the [phonopy documentation](https://phonopy.github.io/phonopy/phonopy-module.html):
> Automatic selection of band paths using [SeeK-path](https://seekpath.readthedocs.io/en/latest/) is invoked by
>
>```
>phonon.auto_band_structure()
>```
Running 
```
janus phonons --struct tests/data/NaCl.cif --band --plot-to-file
```
still correctly generates `NaCl-auto_bands.svg` via `plot_band_structure`, and running
```
poetry add aiida-quantumespresso
```
also installs aiida-quantumespresso successfully.

Downgrade seekpath for aiida-quantumespresso compatibility

---

janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
tests/test_geomopt_cli.py
tests/test_md.py

Resolves #186
1. Changes units from bar to GPa in MD and geomopt (CLI)
2. Moves setting units for `scalar_pressure` when carrying out geometry optimization into calculation module. Previously this was only set for the geomopt CLI command, but this way it's set for anything that calls geomopt e.g. phonons, MD, EoS etc. and for the Python interface, so it's more consistent.
Is there a good way of signposting this? As I mention in #186, for any arbitrary `kwargs` passed to functions, ASE units should be assumed, so this is an exception.
When it's an explicit variable we make it clear, but is there an obvious way when it's passed via (potentially quite convoluted) kwargs e.g. `--minimize-kwargs "{'filter_kwargs': {'scalar_pressure' : x}}"`?
Also worth checking if I've missed obvious cases for …

Change pressure from bar to GPa

---

docs/source/conf.py
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/helpers/log.py
pyproject.toml

Resolves #68
See https://codecarbon.io/ and https://mlco2.github.io/codecarbon/index.html
There are quite a few alternative implementations, but this is one option, which adds a section to the log, based on the [documentation](https://mlco2.github.io/codecarbon/to_logger.html) e.g.:
```
- timestamp: 2024-07-10 17:20:53,779
level: INFO
message:
timestamp: 2024-07-10T17:20:53
project_name: janus-core
run_id: cfd5626c-92bd-400d-bac6-bf2e599d34a0
duration: 0.5009441375732422
emissions: 4.837736120304575e-07
emissions_rate: 9.657236720526065e-07
cpu_power: 7.5
gpu_power: 0.0
ram_power: 5.823497772216797
cpu_energy: 1.0434945424397786e-06
gpu_energy: 0
ram_energy: 8.089440937358934e-07
energy_consumed: 1.8524386361756719e-06
country_name: United Kingdom
country_iso_code: GBR
region: None …
```

Track carbon usage for calculations

---

janus_core/calculations/eos.py
janus_core/calculations/phonons.py
janus_core/cli/eos.py
tests/test_eos_cli.py
tests/test_phonons_cli.py

Resolves #187 & #188
- Passes file prefix from `phonons` to `geom_opt` by default, so the file names for structures written consistent unless overwritten
- Adds option to save generated structures (and initial, potentially optimized structure) when running `eos` in a single file
- Prevents writing via `geom_opt`, as the same structures can be saved more safely within `eos`
- If we also tried to save the optimization trajectory, this would still be overwritten by each structure in turn, but at that point I think it's probably better to recommend dealing with them as separate steps

Fix writing structures for phonons and EoS

---

janus_core/helpers/janus_types.py
janus_core/helpers/mlip_calculators.py
tests/test_eos.py
tests/test_mlip_calculators.py
tests/test_single_point.py

Resolves #95
It's not in the main branch of MACE yet, but as mentioned in #95, there's no reason not to allow `xpu` in theory, so I've added it.
More importantly, in the process of extending the allowed devices, I realised that `device` was not passed to MACE-MP, or MACE-OFF, so this should now be fixed.
Also adds a test that the chosen `device` is valid, as the PyTorch error isn't particularly clear:
```
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with invalid)
```
This should perhaps be three PRs, but they're interconnected and otherwise very minor...

Fix setting devices

---

docs/source/developer_guide/tutorial.rst
janus_core/helpers/janus_types.py
janus_core/helpers/mlip_calculators.py
pyproject.toml
tests/test_mlip_calculators.py
tests/test_single_point.py

Adds optional integration with [ALIGNN](https://github.com/usnistgov/alignn), to be used as worked developer example for how to add a new MLIP to janus-core.
One other thing to consider, which could affect this implementation/the example slightly (although it would be a separate PR), is if we want to standardise the input model.
Currently only `device` is standardised, but if we wanted to do the same for the path to the model (which may be useful/essential for aiida-mlip, @federicazanca?), it would be sensible to do it now, before adding further MLIPs.
To do:
Depends on #195, so may need a minor rebase.

Add ALIGNN as optional MLIP

---

janus_core/calculations/md.py
tests/test_md_cli.py

Resolves #211
Increases precision of most outputs from `.3e` to `.8e`.
We may also want to update `density` and `current_temp`.
In future we could consider making it an option, but given that stats are normally printed relatively infrequently, it's probably not a problem.

Increase precision of MD stats

---

README.md
janus_core/calculations/md.py
janus_core/cli/md.py
tests/test_md.py
tests/test_md_cli.py

Resolves #198
- Replaces final files for each temperature with a single `-final` file, with the same naming conventions as `-traj` and `-stats` files, as well as an option to define the name of this file similarly via `final_file` (`--final-file`).
What were previously individual `-final` files are accessible through reading a specific index from the combined file.
Each structure has the associated temperature (and pressure) that was previously in the file names stored as `info`.

Add final file option for MD

---

README.md
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/cli/descriptors.py
janus_core/cli/geomopt.py
janus_core/helpers/descriptors.py
tests/data/geomopt_config.yml
tests/data/singlepoint_config.yml
tests/test_descriptors_cli.py
tests/test_eos_cli.py
tests/test_geom_opt.py
tests/test_geomopt_cli.py
tests/test_md.py
tests/test_md_cli.py
tests/test_phonons_cli.py
tests/test_post_process.py
tests/test_single_point.py
tests/test_singlepoint_cli.py

Aims to address part of #206, requested by @alinelena:
> -  Change default output extensions from `.xyz` to `.extxyz`

Change default output extensions to extxyz

---

docs/source/apidoc/janus_core.rst
docs/source/developer_guide/tutorial.rst
janus_core/calculations/md.py
janus_core/helpers/correlator.py
janus_core/helpers/janus_types.py
janus_core/helpers/observables.py
tests/test_correlator.py

This PR adds an online correlation algorithm (multi-tau), with stress correlations as user observables. The correlations are,
$$C_{ab}(t) = \frac{1}{T-t}\sum_{t'=1}^{T-t}a(t)b(t+t'),$$
for some values $a$ and $b$, and time lags $t$. The lags (and timestep) are implied by the frequency the correlator is updated in ```run``` controled by ```correlation_parameters[.][3]``` (which could probably use being some TypedDict actually...).
A user may ask for a sequence of correlations by,
```python
correlation_kwargs={
"correlations": [("s_xy", "s_xy")],
"correlation_parameters": [(1, 10, 1, 1)],
},
```
where ```s_xy``` is parsed into an ```Observable``` that can poll ```MolecularDynamics::dyn``` with a ```get``` method.
Correlations are written in ```yaml``` format for now a list of correlations …

Add correlator with stress correlations

---

janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/janus.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/singlepoint.py
janus_core/cli/train.py

Resolves #140
Fixes CLI help messages to prevent docstring dump e.g.
```
Parameters ---------- ctx : Context     Typer (Click) Context. Automatically
set. struct : Path     Path of structure to simulate. arch : Optional[str]
MLIP architecture to use for single point calculations.     Default is
"mace_mp". device : Optional[str]     Device to run model on. Default is
"cpu". model_path : Optional[str]     Path to MLIP model. Default is `None`.
properties : Optional[str]     Physical properties to calculate. Default is
"energy". out : Optional[Path]     Path to save structure with calculated
results. Default is inferred from name     of the structure file.
read_kwargs : Optional[dict[str, Any]]     Keyword arguments to pass to
ase.io.read. Default is {}. calc_kwargs : Optional[dict[str, …
```

Fix CLI help

---

janus_core/helpers/mlip_calculators.py
release.sh

The version is in `sevenn._const`, and seems to be used by them in the same way e.g. https://github.com/MDIL-SNU/SevenNet/blob/main/sevenn/sevenn_logger.py#L244

Add version for sevennet

---

janus_core/cli/utils.py

Resolves #242
Removes "struct" from the `inputs` dict when saving the CLI summary, as this is exactly what `save_struct_calc` is designed to do anyway, and if the `struct` is actually a trajectory, we end up with a duplicate, with binary info printed.

Delete duplicate struct from CLI summary

---

README.md
janus_core/cli/geomopt.py
tests/test_geomopt_cli.py

Resolves #180
- Renames `--vectors-only` to `--opt-cell-lengths` to reduce confusion that this is in addition to optimizing cell positions.
- Renames `--fully-opt` to `--opt-cell-fully` for consistency (if we ever add something like `--opt-cell-angles`, this would be equivalent to both being true, which feels reasonably consistent)
Still open to further suggestions

Rename geomopt flags

---

janus_core/calculations/eos.py
janus_core/calculations/single_point.py

Resolves memory issues due using `deepcopy` when using the same calculator for multiple structures.
`copy` still seemed to be sufficient to resolve #217, as discussed in #218.

Fix calculator copies

---

janus_core/helpers/utils.py
tests/test_geom_opt.py

Resolves #261
Adds check that `arch` in is `calc.parameters` before attempting to write MLIP architecture to info, and tests this.
The test uses the `arch=mace_mp` , rather than `mace`, as setting dispersion for `mace` does not create the same `SumCalculator`, which is the root of the bug. See: https://github.com/ACEsuit/mace/blob/main/mace/calculators/foundations_models.py#L132
The individual MLIP calculators (e.g. `mace.calculators.mace.MACECalculator`) have a `todict` method, which writes the parameters when writing a trajectory format, but this method does not exist for the `SumCalculator`, which is why the error only occurs in certain situations, such as adding dispersion to `mace_mp`, before writing and reading back in the trajectory binary file.

Fix write params

---

janus_core/calculations/descriptors.py
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/singlepoint.py
janus_core/cli/utils.py
tests/test_descriptors.py
tests/test_descriptors_cli.py
tests/test_eos.py
tests/test_eos_cli.py
tests/test_geom_opt.py
tests/test_geomopt_cli.py
tests/test_md.py
tests/test_md_cli.py
tests/test_phonons.py
tests/test_phonons_cli.py
tests/test_single_point.py
tests/test_singlepoint_cli.py

Resolves #250
- Adds summary to CLI for all calculations, made up of sum of task emissions from logger
- Adds emissions of last task to stuct.info at end of each task
To do:
- Defer to #264

Add carbon emissions info and summary

---

.github/workflows/ci.yml
README.md
conftest.py
docs/source/developer_guide/get_started.rst
docs/source/developer_guide/tutorial.rst
docs/source/getting_started/getting_started.rst
pyproject.toml
tox.ini

Resolves #255
Moves chgnet and m3gnet to optional dependencies again, but still tests against these in the CI/with tox.
I need to double check all the installation mechanisms, but this should mean pip/poetry install janus-core should only install MACE, and with extras we can install each MLIP individually, or install all together.
To do:

Update MLIP installations

---

janus_core/calculations/md.py
janus_core/calculations/phonons.py
tests/test_md_cli.py
tests/test_phonons_cli.py

Resolves #273
- Sets `write_results=True` in `minimize_kwargs` for MD and phonon calculations by default
- Also sets default filename for MD, mirroring existing phonon functionality (ensures -opt file prefix matches other MD output files by default)
- This isn't needed for EoS, since we have a separate `write_structures` option that is more general than writing the optimized structure, but performs the same roll
Also moves setting the MD logger filename for consistency

Auto write results

---

janus_core/cli/train.py
janus_core/helpers/train.py
tests/test_singlepoint_cli.py
tests/test_train_cli.py

Resolves #264
- Also adds CLI log/summary in the process
- This seemed to break some tests, as any tests that followed the training (e.g. test_utils, or any Python tests if run in a different order) threw `FileNotFoundError`s, looking for `logs/[model].log`. There may be better solutions but removing these from the `FileHandler`s from the root logger seems to fix this
Depends on #258 (will need rebasing)

Add carbon emissions for training

---

tests/test_mlip_calculators.py
tests/test_single_point.py

Resolves #276
- Uses our saved copy of ALIGNN for singlepoint testing
- Adds skip to MLIP calculator test if a bad zip file is encountered, so the CI doesn't fail if the model download is an issue
- If the remaining two tests are always skipped, we may want to revisit this, but from what I've seen it's rare that the error occurs for every version of Python, so we should still be testing these model inputs in general.
- Tests also seem ok locally, so we should still be able to keep track of any breaking changes

Update ALIGNN testing

---

README.md
docs/source/apidoc/janus_core.rst
janus_core/calculations/base.py
janus_core/calculations/descriptors.py
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/singlepoint.py
janus_core/cli/types.py
janus_core/cli/utils.py
janus_core/helpers/utils.py
tests/test_filenamemixin.py
tests/test_md_cli.py

Resolves #279
- Moves parsing of `struct`/`struct_path` and attaching calculators to new base class, which all calculations inherit from
- Provides access to file stems within (hence resolving #279)
- Also means we don't need to do everything via SinglePoint
To do:
- Mostly covered via CLIs, which all use `struct_path`, but we can update MD, for example, to ensure #279 is actually resolved
- `test_filenamemixin` needs updating
- API list needs updating

Add file inputs to all calculations

---

janus_core/calculations/md.py
tests/test_md_cli.py

Resolves #286
Contrary to my comment in the linked issue, I think having `self.file_prefix` become the default if it's not otherwise specified is probably necessary.
This means we can only set the parameter prefix when the input `file_prefix` is known, on init.
I don't think this is a problem though, as it's not something that makes sense for the user to update after init, since we can't usually distinguish between an output file that was built from one that the user defined anyway.

Fix MD file names

---

janus_core/calculations/descriptors.py
tests/test_descriptors_cli.py

Fixes repeated log messages for settings when calculating descriptors for trajectory, and minor update to testing the log.

Remove duplicated descriptors log

---

janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/singlepoint.py
janus_core/cli/utils.py
janus_core/helpers/utils.py
tests/test_utils.py

Since #283, the information that used to be passed to `SinglePoint` was duplicated, which also led to weird yaml aliases/anchors for the duplicated dictionaries.
This fixes this by removing duplicate keys from `inputs`, and also tides up the summary to handle it all in one place.

Fix summary duplication

---

janus_core/helpers/utils.py
tests/test_geomopt_cli.py

Resolves #290
Fixes setting default for `set_calc` to be set to `True` if `struct_path` is specified.
This was supposed to be the case already, but was being overwritten by the structures read from file having `SinglePointCalculators `attached, due to their saved results, leading to errors.
Test added fails before fix implemented.

Fix set_calc default when reading structure file

---

janus_core/calculations/descriptors.py
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/helpers/utils.py
tests/test_descriptors_cli.py
tests/test_eos_cli.py
tests/test_geomopt_cli.py
tests/test_md_cli.py
tests/test_phonons_cli.py
tests/test_singlepoint_cli.py

Resolves #269
Anything that uses `build_filename` should now automatically create the parent directory if it does not already exist.
This also extends to filenames given through `write_kwargs` etc., since these did not previously use the `FileNameMixin`.

Make directories when building filenames

---

README.md
docs/source/user_guide/command_line.rst
janus_core/calculations/base.py
janus_core/calculations/descriptors.py
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/singlepoint.py
janus_core/cli/train.py
janus_core/cli/types.py
janus_core/helpers/train.py
tests/test_descriptors_cli.py
tests/test_eos_cli.py
tests/test_geomopt_cli.py
tests/test_md_cli.py
tests/test_phonons_cli.py
tests/test_singlepoint_cli.py
tests/test_train_cli.py
tests/utils.py

Resolves #132
As mentioned in the issue, sharing the summary is relatively straightforward, but extra changes were needed to use the `FileNameMixin` to set the log filename to be consistent with other output files.
Since the default filename moves into the Python, I added an additional flag that controls the logging, so a filename isn't required. 
Loosely depends on fixing #279, for correct documentation, and tests will then require updating following a fix.

Set consistent log and summary file names

---

janus_core/calculations/base.py

Adds same functionality as all other outputs to log files, allowing any required directories to be created, which was missed due to overlapping PRs.

Create missing directories for logging

---

docs/source/user_guide/command_line.rst
janus_core/calculations/md.py
janus_core/cli/md.py
janus_core/helpers/utils.py
tests/test_md.py
tests/test_md_cli.py

Resolves #169
Adds auto restart option for MD, which generates `restart_stem` based on inputs (including `file_prefix` and `restart_stem`), and if restarting simulation, uses the most recent matching file for the input structure.
Also includes fixes for:
- `prefix_override`, which threw errors if given a `Path`s (e.g. anything via `--restart-stem`)
- How `restart_stem` was used, as currently for `restart_stem=stem`, files of the form `stem-T300.0-res-1.extxyz` are created, the same as the old usage of `struct_name`. With these changes, they should now be `stem-1.extxyz`
Note: the limit after restarting is the effectively the same as before - however far the previous simulation got + the full `steps` input (e.g. for `NaCl-nvt-T300.0-res-100.extxyz`, with `--steps 1000`, the last step would …

Add auto restart

---

janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/singlepoint.py
janus_core/cli/train.py
janus_core/cli/types.py
pyproject.toml

I'd hoped that this could include all forms of `Union`, but as of [typer 0.12.2](https://github.com/fastapi/typer/releases/tag/0.12.2), `Union[x | None] `/ `Optional` typing should be fully supported.
I think we were actually making use of this to some extent already, which could lead to errors, so this bumps the minimum version of typer to ensure it is supported, included fixes in subsequent minor releases, as well as adding `Optional` everywhere that was missing.

Update typer and Optional CLI parameters

---

janus_core/cli/singlepoint.py
tests/test_singlepoint_cli.py

At some point the other singlepoint inputs (e.g. `properties`) got lost from the summary.
Duplicates should still be dealt with within `save_struct_calc`, as for all other calculations.

Fix singlepoint summary

---

docs/source/user_guide/command_line.rst
janus_core/calculations/phonons.py
janus_core/cli/phonons.py
janus_core/cli/utils.py
tests/test_phonons_cli.py

Starting point to resolves #305

Add mesh CLI option and fix thermal mesh

---

janus_core/calculations/descriptors.py
tests/test_descriptors.py

Resolves #309
The solution for the `SumCalculator` case isn't the nicest, but hopefully the checks are specific enough that it's reasonable.
The two added tests both fail prior to the subsequent changes :
```
FAILED tests/test_descriptors.py::test_dispersion - AttributeError: 'SumCalculator' object has no attribute 'get_descriptors'
FAILED tests/test_descriptors.py::test_not_implemented_error - Failed: DID NOT RAISE <class 'NotImplementedError'>
```

Fix unimplemented descriptors

---

janus_core/calculations/phonons.py
janus_core/cli/phonons.py
janus_core/helpers/utils.py
pyproject.toml

Closes #268 
Adds a progress bar to phonon calculations using `tqdm`, which is already a dependency. A new argument was added to `Phonons.__init__` to control the presence of this feature, disabled by default to minimise impact on code in general. However, the progress bar is always enabled for CLI.
One issue that I and @ajjackson have noted is that the bar only shows the progress over displacements, meaning that when bands, DOS, or PDOS are chosen to be calculated, the 100% bar just continues sitting there despite the prolonged calculations. This could be confusing to users. One solution could be writing to stdout before/after the progress bar appears, saying what the bar is for, but we weren't sure what the best path forward is. What do you think?
Additionally, I should probably mention …

Add progress bar to phonon calculations

---

janus_core/calculations/geom_opt.py
janus_core/calculations/phonons.py
janus_core/cli/geomopt.py
janus_core/helpers/utils.py
tests/test_geomopt_cli.py
tests/test_phonons.py

Address part of #310
- Adds `snap_symmetry` function to utils, currently used explicitly in geom_opt, and indirectly for phonons
- Currently this only applies after optimization. As discussed with @oerc0122 and others, it may also be useful to apply this before optimization, but I'm not sure if that should be built in to this, or simply an option via the Python utils, which this allows
- Change defaults to save optimized file automatically
- ~Add displacement_kwargs, passed to `generate_displacements`~
These could arguably be three separate PRs, but the latter two will be useful for testing `snap_symmetry` (e.g. setting the `seed`), so I've kept them together for now.
To do:

Add symmetry refining

---

docs/source/conf.py
janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/singlepoint.py
janus_core/cli/train.py
janus_core/cli/types.py
janus_core/cli/utils.py
janus_core/helpers/mlip_calculators.py

Resolves #267
A lot of this has turned out to be similar to #272. I hadn't appreciated that our current structure with individual modules for each command (`janus_core.cli.singlepoint` etc.) meant that we actually already shared a lot of the structure with the solutions I linked, but to get their benefits we still need to move imports into the `@app.command()` functions.
I think moving `from janus_core.calculations.single_point import SinglePoint` etc. into these functions is all we really need for a much more responsive CLI, but I also moved the utils imports to keep the required CLI command modules as clean as possible.
I've then added `TYPE_CHECKING` for the the CLI types and utils, to minimize imports needed for defining the CLI options, without need to worry too much about other …

Add lazy imports for CLI and calculators

---

.gitignore
janus_core/calculations/eos.py
janus_core/cli/eos.py
tests/test_eos.py
tests/test_eos_cli.py

Adding EoS plotting

---

README.md
docs/source/developer_guide/tutorial.rst
docs/source/getting_started/getting_started.rst

Should have been part of #337 really.
For future reference, `tutorial.rst` doesn't necessarily need updating, since it's just an example, but the README and getting started should be consistent with current requirements.

Update sevennet version in docs

---

CITATION.cff
pyproject.toml

This should be picked up automatically by [zenodo](https://support.zenodo.org/help/en-gb/24-github-integration/96-how-does-a-citation-cff-file-affect-metadata-of-my-github-release), which should fix the list of authors.
Feel free to directly push any more details, both generally and your specific author details e.g. orcids.

Add citation

---

tests/test_phonons.py

Changes introduced in #326 meant that `Cl4Na4-opt.extxyz` was created in a couple of phonon tests, but not cleaned up.

Clean up test output

---

janus_core/calculations/base.py
janus_core/calculations/descriptors.py
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/singlepoint.py
janus_core/cli/train.py
janus_core/helpers/log.py
janus_core/helpers/train.py
tests/test_descriptors_cli.py
tests/test_eos_cli.py
tests/test_geomopt_cli.py
tests/test_md_cli.py
tests/test_phonons_cli.py
tests/test_singlepoint_cli.py
tests/test_train_cli.py

This doesn't solve the CI problem in #334, but for real users, this allows disabling carbon tracking, since this may require sudo access that they may not want to provide.
There are ways to add a timeout when we set up the carbon tracker, which would be another solution, which would actually fix the CI, but doing it in a general way sounds non-trivial (e.g. [discussion](https://discuss.python.org/t/input-function-with-timeout/44034), [potential solutions](https://stackoverflow.com/questions/492519/timeout-on-a-function-call) are not necessarily cross-platform).

Make carbon tracking optional

---

janus_core/processing/post_process.py
tests/test_post_process.py

Add lags to vafs

---

docs/source/user_guide/command_line.rst
janus_core/calculations/phonons.py
janus_core/cli/phonons.py
tests/test_phonons_cli.py

As discussed, and mentioned in #310, I had a try at adding support for non-diagonal supercells to phonon calculations. The Python API change is small: simply adding support for lists of length 9, which are then turned into a 3x3 matrix. The CLI API is much trickier due to the restrictions that typer/click impose ([certain hacks](https://stackoverflow.com/questions/48391777/nargs-equivalent-for-options-in-click) notwithstanding); for now, I and @ajjackson decided to require the supercell input to be a whitespace-separated string, e.g. `"1 2 3"`), which would have to be passed in as a string. The other option we considered was having two different options for the two cases, e.g. `--supercell-diagonal` and `--supercell-nondiagonal`. However, we aren't sure what would be the best approach; …

Add support for non-diagonal supercells

---

janus_core/calculations/base.py
janus_core/calculations/descriptors.py
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/helpers/mlip_calculators.py
janus_core/helpers/struct_io.py
janus_core/helpers/utils.py
janus_core/training/train.py
tests/test_utils.py

Also use for single instances of `dict` `None`-ness check.

Slight change to none_to_dict to avoid nesting brackets.

---

README.md
docs/source/apidoc/janus_core.rst
docs/source/user_guide/command_line.rst
janus_core/cli/janus.py
janus_core/cli/preprocess.py
janus_core/helpers/utils.py
janus_core/training/preprocess.py
janus_core/training/train.py
tests/data/mlip_preprocess.yml
tests/data/mlip_preprocess_stats.yml
tests/test_preprocess_cli.py
tests/test_train_cli.py

Resolves #37
This probably should should probably be moved to `training` after #341 is merged.
This also currently relies on us passing each config option. I'm hoping we should be able to update this (see [MACE PR](https://github.com/ACEsuit/mace/pull/664)) to allow the config to be passed straight through, as we do for training.

Add preprocessing training data

---

README.md
docs/source/user_guide/command_line.rst
docs/source/user_guide/python.rst
janus_core/helpers/mlip_calculators.py
janus_core/helpers/struct_io.py
tests/test_mlip_calculators.py
tests/test_singlepoint_cli.py
tests/test_utils.py

Resolves #327
For `model_path` (or equivalent inputs e,g, `model`), this adds `mlip_model` as an info label when structures are output.
For strings and paths, this is fine. For already-loaded torch models, it's less clear what the best label is, so I'm open to alternatives.
This will also interact with any implementation of #240, but we can deal with that when we come to it.
@alinelena, was the suggested `info['{arch}_{model}'] = model` replacing `info["arch"]` or additional? To me it doesn't make sense to have `"{arch}_model"` as well as `"arch"`, which is how I originally interpreted it, but perhaps it makes sense to combine them into a single info label, which I just realised may be what you meant.

Save model info

---

docs/source/apidoc/janus_core.rst
docs/source/conf.py
docs/source/developer_guide/tutorial.rst
janus_core/calculations/md.py
janus_core/helpers/janus_types.py
janus_core/helpers/utils.py
janus_core/processing/correlator.py
janus_core/processing/observables.py
janus_core/processing/post_process.py
tests/test_correlator.py
tests/test_utils.py

This adds a Velocity observable capable of averaging over supplied components ```x, y, z``` and atom lists. The behaviour is abstracted so also for stress we can obtain shear stress correlations $\langle \sigma_{xy}\sigma_{xy}\rangle+\langle \sigma_{yz}\sigma_{yz}\rangle+\langle \sigma_{zx}\sigma_{zx}\rangle$ with the built in ```ShearStress === Stress(['xy', 'yz', 'zx'])```
- ci tests now test against post-process vaf, dependent on changes to it #284 .
- I used the ShearStress observable to get experimental viscosity for LiF which could be an example perhaps along with the VAF.

Adds Velocity, ShearStress, StressDiagonal, observables

---

janus_core/calculations/base.py
janus_core/calculations/md.py
tests/test_md_cli.py

Resolves #365
Updates the default MD `write_kwargs["columns"]` to output both `forces` and (for example) `mace_mp_forces`, to be consistent with all other methods, unless `invalidate_calc` is set as a `write_kwarg`.
Also updates the architecture for all calculations to match the structure's calculator architecture, which means if, for example, we pass `Singlepoint.struct` when creating an `MD` object, the `MD.arch` is set to match `Singlepoint.arch`, rather than the default, which is misleading. (Arguably this could be a separate PR, but it currently only substantially affects changes used in this. It is a separate commit though, so I can split it out if we like).

Add MD forces by default

---

.github/workflows/ci.yml

Resolves #372
See also, discussion in `pymatgen`: https://github.com/materialsproject/pymatgen/issues/4243
I think unsetting `CI` is the only solution, as I think otherwise `os.getenv("CI") is not None` evaluates to `True`, even if `CI` is set to `""`, `False`, etc.
This change should be reverted once #374 is implemented, as we should be able to update monty to include the fix: https://github.com/materialsvirtuallab/monty/pull/735.

Implement temporary fix for CI

---

docs/source/user_guide/index.rst
docs/source/user_guide/troubleshooting.rst
janus_core/calculations/base.py
janus_core/calculations/descriptors.py
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/calculations/md.py
janus_core/calculations/phonons.py
janus_core/calculations/single_point.py
janus_core/helpers/log.py
janus_core/helpers/utils.py
janus_core/training/preprocess.py
janus_core/training/train.py
tests/test_log.py

Resolves #368
Also resolves various issues relating to logging/tracking, including:
- Setting `attach_logger` default based on whether filename is in `log_kwargs`, which we effectively already did, but did not say we were doing, which is confusing
- Require logging for carbon tracking, which (again) we essentially already did
- Allow kwargs to be passed to carbon tracking, which allows default power etc. to be passed (this may soon provide another alternative to bypass MacOS sudo requests, although not yet)
- Add troubleshooting section for carbon tracking issues
- Raise an error after carbon tracker initialisation if errors occurred, as otherwise it doesn't raise until the calculation is run

Improve logging and carbon tracking consistency

---

janus_core/processing/correlator.py
janus_core/processing/observables.py

- Addresses #357 
- Also removes the flattening in ```Velocity``` to preserve dimension for general use cases.

Comment correlation algorithm, remove flattening of Velocity observable

---

.github/workflows/publish-on-pypi.yml
pyproject.toml

I think by setting the `permissions` explicitly for `id-token`, it removed write permissions, which blocked the release action (previously this was successful, but publishing to PyPI was not).
Adding this back in seemed to work on my fork.

Fix release

---

.github/workflows/ci.yml
.github/workflows/mac.yml
README.md
docs/source/getting_started/getting_started.rst
janus_core/calculations/eos.py
janus_core/calculations/geom_opt.py
janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/janus.py
janus_core/cli/md.py
janus_core/cli/phonons.py
janus_core/cli/preprocess.py
janus_core/cli/singlepoint.py
janus_core/cli/train.py
janus_core/cli/types.py
janus_core/helpers/janus_types.py
janus_core/helpers/mlip_calculators.py
janus_core/helpers/stats.py
janus_core/helpers/struct_io.py
janus_core/helpers/utils.py
janus_core/processing/correlator.py
janus_core/processing/post_process.py
pyproject.toml
tests/test_md_cli.py
tox.ini

Resolves #374
As I mention in the issue, we should think carefully about when we want to merge this, but I wanted to check it's also a viable solution to our CI problems, and these changes shouldn't clash too much with ongoing work that may be merged before this.
- Drops Python 3.9 support, remove Python 3.9 from testing matrices, and apply fixes to satisfy `ruff`
- Adds in missing `from __future__ import annotations`, which relied on a fix only available for Python 3.10+
Note: if merged after #376, those changes can be reverted.

Drop Python 3.9 support

---

docs/source/user_guide/python.rst
tests/test_ase_calculators.py

Test and document external calculators

---

.github/workflows/mac.yml

"Fixes" issues with uploading coverage from MacOS tests by removing coverage check, since it's just duplicating coverage we calculate and upload on Linux.

Remove coverage from MacOS tests

---

pyproject.toml

Required for using uv virtual environments with Jupyter notebooks

Add ipykernel dev dependency

---

docs/source/developer_guide/get_started.rst

Resolves #391
Mostly based on various (linked) parts of the docs, but some comments borrowed from https://github.com/astral-sh/uv/issues/9219.

Add uv description

---

janus_core/calculations/single_point.py
janus_core/cli/singlepoint.py

Closes #403
Adds progress bars identical to #319 to single point calculations when applied to multiple frames:
Because each property is calculated in a separate loop, there is one progress bar per property for now. I'm happy to try to make it one overall progress bar if that's preferred.

Add progress bars to single point calculations

---

docs/source/developer_guide/get_started.rst

By default, uv will try to install Python 3.13 on a system with no existing Python 3 (e.g. scarf, before modules have been loaded).
Specifying different Python versions with `-p` is discussed in the section below, but since people may copy and paste these to get started, it's probably safest to specify this here explicitly.

Specify Python version in dev docs

---

docs/source/conf.py
docs/source/user_guide/troubleshooting.rst
pyproject.toml

Add installation troubleshooting

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/publish-on-pypi.yml
README.md
docs/Makefile
docs/source/conf.py
docs/source/developer_guide/get_started.rst
docs/source/index.rst
docs/source/tutorials/eos.ipynb
docs/source/tutorials/geom_opt.ipynb
docs/source/tutorials/index.rst
docs/source/tutorials/md.ipynb
docs/source/tutorials/phonons.ipynb
docs/source/tutorials/single_point.ipynb
docs/source/user_guide/python.rst
pyproject.toml

Resolves #386
Adds basic tutorials from https://github.com/stfc/janus-tutorials, with minor formatting changes.
These are built as part of the publishing workflow, so must run successfully before janus-core is published to PyPI.
An example: https://elliottkasoar.github.io/janus-core/tutorials/single_point.html
To do:

Test tutorials

---

docs/source/user_guide/command_line.rst
janus_core/calculations/md.py
janus_core/helpers/janus_types.py
janus_core/processing/post_process.py
tests/test_correlator.py
tests/test_post_process.py

I found I could not easily request partial VAFs on the CLI by element names (or StartStopStep likes). But instead would have to write all the indices down, which can be automated in shell but is quite unwieldy. So I implemented selecting vaf atoms by element name. Hopefully a useful addition.
Partial VAFs can be obtained in the CLI like so,
```shell
janus md --ensemble nve --struct tests/data/NaCl.cif --steps 100 --traj-every 10\
--post-process-kwargs "{'vaf_compute': True, 'vaf_atoms': (('Na',), ('Cl',)), 'vaf_output_files': ('vaf_na.dat', 'vaf_cl.dat')}"
```
where 'Na' and 'Cl' are expanded to indices of those elements in the trajectory.
Also add some documentation for post-processing.

Adds post-process cli guide, specifying vafs by element name

---

janus_core/calculations/md.py
janus_core/cli/md.py
tests/test_md.py

Fixes #417 
Fixes #424
`NPH` stats output no longer shows `Target_T` column, and `Target_P` header removed from `NVT_NH` stats output (#424). `NPH` and `NVT_NH` now inherit from `MolecularDynamics` instead of `NPT` to simplify logging changes.
`NPH` fixed to only enable barostat instead of thermostat (#417), as changes for the two issues overlapped a lot.
NPH enthalpy conservation:

Fix NPH and NVT_NH

---

pyproject.toml

`sphinx==8.2.0` is incompatible with `sphinx-autodoc-typehints==3.0.1`, and newer versions have dropped support for Python 3.10
See: https://github.com/sphinx-doc/sphinx/issues/13362 and https://github.com/tox-dev/sphinx-autodoc-typehints/issues/523

Add upper limit for sphinx

---

.github/workflows/docs.yml
.github/workflows/publish-on-pypi.yml

Resolves #419
There may be better solutions, but given that the docs only take a couple of minutes to run, I think for now just allowing them to run sequentially (which I think is what should happen with these changes) is fine.

Remove cancel-in-progress for docs

---

janus_core/calculations/md.py
tests/test_md.py
tests/test_md_cli.py

Fixes #436 
Adds a check to raise an error if the temperature step time is shorter than 1 timestep. Also prints a debug message if the temperature step time is rounded significantly.
Tests have been added to verify the error is raised correctly, and existing tests using temperature step times shorter than 1 timestep have been updated.

Prevent temp steps less than timestep

---

.github/workflows/ci-dev.yml
.github/workflows/ci.yml

This should test against up-to-date development versions of ASE and MACE during CI.
It shouldn't fail the CI if the tests fail, so that we can have a warning about upcoming breaking changes.

Add CI test against development versions

---

janus_core/helpers/struct_io.py
tests/test_geom_opt.py

There was almost a fix, but it should have been `("extxyz",)`, so `"xyz"` is still included.
To do:

Fix writing xyz files

---

docs/source/user_guide/command_line.rst
janus_core/calculations/geom_opt.py
janus_core/calculations/single_point.py
janus_core/cli/geomopt.py
janus_core/cli/singlepoint.py
janus_core/cli/types.py
tests/test_geom_opt.py
tests/test_geomopt_cli.py

Adds the option to provide a file prefix that is used for all of the files produced by single point and geometry optimisations. Since this can include a directory, it helps to allow the option to create a results directory for https://github.com/stfc/janus-core/issues/359#issuecomment-2684974380.

Add file prefix options to singlepoint and geomopt

---

janus_core/cli/descriptors.py
janus_core/cli/eos.py
janus_core/cli/geomopt.py
janus_core/cli/md.py
janus_core/cli/neb.py
janus_core/cli/phonons.py
janus_core/cli/preprocess.py
janus_core/cli/singlepoint.py
janus_core/cli/train.py
janus_core/cli/utils.py
tests/test_descriptors_cli.py
tests/test_eos_cli.py
tests/test_geomopt_cli.py
tests/test_md_cli.py
tests/test_neb_cli.py
tests/test_phonons_cli.py
tests/test_preprocess_cli.py
tests/test_singlepoint_cli.py
tests/test_train_cli.py

This saves the input parameters to CLI commands in the summary.
As described in #128, I think it makes most sense to save the config before any defaults are applied.
This is partly because where defaults are set varies between the CLI and Python modules for each command, accessing the "final" value of each parameter would not be trivial.
It also ensures consistency if this is used for a new config file, since in some cases, whether the parameter is using a default or has been explicitly set change behaviours, which would no longer be distinguishable if we stored the default.
In combination with #454. hopefully this won't be a problem in addressing the original #128 issue.
E.g.:
```
janus geomopt --struct tests/data/NaCl.cif --arch mace_mp --model-path small --opt-cell-lengths --write-traj …
```

Save input configuration

---

janus_core/calculations/base.py
janus_core/calculations/md.py
tests/test_md_cli.py

Resolves #433
Saves temperature (which ASE gets from momenta, so requires minimal calculation), and, where relevant, target temperature, to `Atoms.info`.
This is then written out to the trajectory, results and final files.
Also removes (target) pressure from the final state info, to be consistent with other outputs. We may want to similarly add in the real and target pressure.
To do:

Fix temperature saved during MD

---

docs/source/user_guide/command_line.rst
janus_core/calculations/md.py
janus_core/cli/md.py
janus_core/cli/types.py
janus_core/cli/utils.py
janus_core/helpers/janus_types.py
janus_core/processing/correlator.py
janus_core/processing/observables.py
tests/test_correlator.py
tests/test_md_cli.py
tests/test_utils.py

- Adds CLI arguments for requesting correlations defined in ```janus_core.processing.observables```.
- Adds default values for ```blocks=1```, ```points=1```, ```averaging=1``` and ```update_frequency=1``` in```janus_core.processing.correlator.Correlation```.
- Add default for ```Velocity``` (all components, all atoms)
- Fixes docstring in ```md.py```.
Last thing to do is add text in the user_guide 
---
Currently this is example functionality
```shell
janus md \
--ensemble nve --struct tests/data/NaCl.cif \
--steps 10 --correlation-kwargs \
"{'vaf1': {'a': 'velocity', 'points': 10}, 'vaf_x': {'a': 'velocity', 'update_frequency': 2, 'points': 10, 'a_kwargs': {'components': ['x']}, 'b_kwargs': '.'}}"
```
Syntax
- If one of 'a' and 'b' is omitted it is duplicated. 
- The special "ditto" …

Add Correlator CLI and defaults

---

pyproject.toml

This reverts commit de6144d7693c1dc7553cfc98f1eb9b9597f2998b.
Tutorials failed to build, possibly due to changes to the output file locations.

Revert "bump version for release 0.7.5"

---

docs/source/tutorials/md.ipynb

Tutorials are failing to build, as they reference output files without their output directory. I'm testing locally too, but I think this addresses the files which don't exist.

Fix reading output in tutorial

---

docs/source/tutorials/cli/geomopt.ipynb
docs/source/tutorials/cli/singlepoint.ipynb

Tries to introduce:
- Getting help (janus and commands)
- Running single point calculations
- Building and using config files
- Running calculations with different MLIPs
- Arguable could come later, but helps explain what info the results actually contains, so it felt useful here
- Summary and log files
- Reusing configurations via the summary
- Again, in some ways not a priority, but I use it as a way to show different calculations and multiple structures
- Setting kwargs via --kwargs and, preferably, a config file

Add singlepoint and geomopt CLI tutorials

---

docs/source/tutorials/cli/geomopt.ipynb
docs/source/tutorials/cli/md.ipynb
docs/source/tutorials/cli/neb.ipynb
docs/source/tutorials/cli/phonons.ipynb
docs/source/tutorials/cli/singlepoint.ipynb

Resolves #485
This adds a few changes needed to run successfully in Colab:
- Downgrading NumPy, which is installed by default
- This also requires restarting the session, which is done automatically as part of these changes
- Downgrade torch
- MACE should work with torch 2.6, but our current version of SevenNet does not, which I think it mostly because MACE forces an old version of e3nn (MACE introduced a [workaround](https://github.com/ACEsuit/mace/issues/555), whereas SevenNet has recently upgraded e3nn  - see #490)
- We also need to remove torchaudio (and also torchvision, to be safe), as this is pre-installed, but raises an error
- Ensures the `./data` exists for geomopt.ipynb
- Disables all carbon tracking, since this seems to throw errors in Colab (may be worth revisiting, at least …

Fix CLI tutorials for Colab

---

janus_core/cli/eos.py
janus_core/cli/md.py
janus_core/cli/singlepoint.py
janus_core/cli/types.py

Resolves #464
This results in something like:
```
╭─ Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ *  --struct                          PATH                                                                     Path of structure to simulate. [default: None] [required]               │
│    --arch                            [mace|mace_mp|mace_off|m3gnet|chgnet|alignn|sevennet|nequip|dpa3|orb|ma  MLIP architecture to use for calculations. [default: mace_mp]           │
│                                      ttersim]                                                                                                                                         │
│ …
```

Use click choices in CLI

---

docs/source/conf.py

(Mostly) resolves #443
Uses author list from pyproject.toml for documentation copyright authors. This doesn't sync with CITATION.cff yet, but it's one less place to update.

Use pyproject authors for copyright

---

docs/source/tutorials/python/eos.ipynb
docs/source/tutorials/python/geom_opt.ipynb
docs/source/tutorials/python/md.ipynb
docs/source/tutorials/python/neb.ipynb
docs/source/tutorials/python/phonons.ipynb
docs/source/tutorials/python/single_point.ipynb

Adds Colab torch/numpy fixes for Python tutorials, as introduced in #492 for the CLI equivalents.

Fix Python tutorials for Colab

---

README.md

Resolves #506
Unfortunately we can't separate the success of the docs from the publishing success, but at least it will link to the docs again, even if it currently shows are failing (in general this should be rare...).

Fix docs status badge

---

tests/test_mlip_calculators.py

`BadZipFile` doesn't have a `.msg`, which this line was supposed to fix, but I implemented the fix in the wrong order.

Fix catching BadZipFile

---

README.md

A small update to the tutorial links in the README, as the python tutorials have been moved to a subdirectory

Update README tutorial links (source files moved)

---

tests/test_mlip_calculators.py
tests/test_single_point.py

Addresses comment from @oerc0122 in  #516, and fixes attribute from `URLError`, which I thought I'd corrected, but  slipped through.

Fix error catching in tests

---

janus_core/calculations/neb.py
janus_core/cli/neb.py
tests/test_neb.py

In preparation for #529, some tidying up of NEB error handling:
- Move all error catching into Python calculation, as there's nothing that we checked in the CLI that shouldn't be checked in the Python (and in the case of specifying the initial/final and full path, this was already the checked).
- Add a few new Python tests to cover cases where errors should be raised

Tidy NEB error handling and tests

---

docs/source/conf.py

This doesn't throw an error, but we currently get two types of warning when building the docs, one of which we can fix with `intersphinx`, and one which needs to be ignored:
```
<unknown>:1: WARNING: py:class reference target not found: rich.progress.Progress [ref.class]
```
```
/Users/elliottkasoar/Documents/PSDI/janus-core/docs/source/apidoc/janus_core.rst:252: WARNING: py:class reference target not found: Progress [ref.class]
```

Fix documentation warnings

---

.github/workflows/windows.yml
README.md
docs/source/getting_started/getting_started.rst
docs/source/user_guide/installation.rst
pyproject.toml

MLIPs that depend on `dgl` haven't actually been working on Windows, but the tests pass due to the skips (e.g. https://github.com/stfc/janus-core/actions/runs/14931210938/job/41947679259).
```
Run uv sync --extra mace --extra m3gnet --extra alignn
Resolved 386 packages in 2ms
error: Distribution `dgl==2.1.0 @ registry+[https://pypi.org/simple`](https://pypi.org/simple%60) can't be installed because it doesn't have a source distribution or wheel for the current platform
hint: You're on Windows (`win_amd64`), but `dgl` (v2.1.0) only has wheels for the following platforms: `manylinux1_x86_64`, `manylinux2014_aarch64`, `macosx_11_0_arm64`, `macosx_11_0_x86_64`
```
In theory there are other versions of dgl published for Windows, but since they've both stopped publishing on PyPI and stopped …

Remove DGL MLIPs for Windows

---

janus_core/helpers/stats.py
tests/test_stats.py

This is perhaps one way to address #442
I think there are 3 points:
- 'Exact' (case insensitive) matches should always work e.g. ```t``` or ```T``` should match ```t``` (temperature) rather that ```Step```. Currently I don't think you can get temperature from a string since ```'t'``` always goes to step and the units are stripped so ```'T [K]'``` throws ```IndexError: T K not found in labels```.
- Fuzzy matching should be preserved, it is useful to keep 'vol' returning Volume I think.
- But what to do about multiple fuzzy matches?  Currently I return the shortest matching key (so ```'TI'``` matches ```'Time'``` not ```'Real Time'```.
Maybe there are better ways to handle multiple fuzzy matches?

Check exact and fuzzy matches in Stats

---

janus_core/calculations/geom_opt.py
tests/test_geom_opt.py

Resolves #522
(Tests added fail before changes added in the second commit)
As discussed in the issue, there are different options for solving this. For now, this simply creates the directory for the trajectory file, which allows initialisation of the dynamics as usual.
The other alternative discussed with @oerc0122 was potentially initialising the trajectory file to be written in a temporary directory, but I think that has the potential to be more confusing if a user inspects the `Trajectory` object, and the way that the [trajectory is attached to the dynamics](https://gitlab.com/ase/ase/-/blob/master/ase/optimize/optimize.py?ref_type=heads#L126) may make this quite messy.

Fix writing optimisation trajectory to new directory

---

.github/workflows/ci.yml
docs/source/user_guide/installation.rst

Fixes warning from underline being too short, and missing mace imports, which have knock-on effects for training/pre-processing.

Fix docs warnings

---

janus_core/cli/geomopt.py
janus_core/cli/types.py
janus_core/cli/utils.py

- Hides deprecated CLI options
- Prints warning if deprecated option is used
- ~Updates CLI dependencies~ (not strictly needed, but relevant, and helped establish that #547 still cannot be used with typer, even with click 8.2 installed)
- Removed, as there's currently a bug related to help with no commands (i.e. just running `janus`): https://github.com/fastapi/typer/pull/1240

Add warning for deprecated CLI parameters

---

janus_core/cli/types.py

Resolves #551
Clarifies the `--minimize-kwargs` help, used by `janus geomopt`, `janus md`, etc. due to ambiguity between geometry optimiser and ASE optimiser class keyword arguments (`minimise_kwargs` vs `opt_kwargs`).
Also states more explicitly that other kwargs e.g. `filter_kwargs` are set this way.

Update minimize_kwargs CLI help

---

docs/source/developer_guide/tutorial.rst

As requested in #557.
Includes some assumptions that #562 is merged.

Add parameter deprecation guide

---

.github/workflows/ci-dev.yml

Adds missing `--no-sync` option to `uv run` in dev CI workflow, which is required to prevent numpy being upgraded on `uv run`.
See: https://github.com/stfc/janus-core/pull/574#discussion_r2228786339

Fix dev CI

---

.github/workflows/ci.yml
.github/workflows/mac.yml
docs/source/conf.py
docs/source/user_guide/get_started.rst
docs/source/user_guide/python.rst
janus_core/helpers/mlip_calculators.py
pyproject.toml
tests/test_descriptors.py
tests/test_mlip_calculators.py
tests/test_single_point.py
tests/test_singlepoint_cli.py

Resolves #567
- Adds `d3` optional extra
- Adds `dispersion` and `dispersion_kwargs` to `choose_calculator`, allowing any calculator to be converted into a `SumCalculator` composed of the original calculator, and the `TorchDFTD3Calculator`.
- This is not currently exposed directly to calculations, but can be set via `calc_kwargs`. The option remains open to add these as full parameters to all calculations in the future, and it's documented as is for now
- Adds `_d3` label to `calc.parameters.arch` e.g. `mace_mp_d3_energy`. This is also the case for values that don't depend on the dispersion, e.g. descriptors, but I thought it might be better to be consistent with the `arch` label. I'm also very happy to revert to `mace_mp_descriptors` if this is preferable.
- For `mace_mp`, I use their …

Add calculator option for dispersion correction
